# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'MayTermApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MayTermApp
    pod 'SwiftSocket'

  target 'MayTermAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MayTermAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
